services:
  postgres:
    image: postgres:16-alpine
    container_name: ad-agency-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ad_agency_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rameez
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  ai-service:
    build:
      context: .
      dockerfile: apps/ai-service/Dockerfile
    env_file:
      - .env
    ports:
      - "4010:4010"
    depends_on:
      - postgres

volumes:
  postgres_data:
